<a href="https://colab.research.google.com/github/Narissarach/data_viz_2022/blob/main/Christmas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## HW 3 

1. สร้าง array ที่เป็นรูปต้น Christmas
2. slice เลข 1 ออกมาจาก array HW3

In [41]:
HW3 = np.zeros((10,10))
HW3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [43]:
HW3[::4,2] = 6
HW3[::4,4] = 5
HW3[::4,6] = 1
HW3[::4,8] = 1
HW3

array([[0., 0., 6., 0., 5., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 6., 0., 5., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 6., 0., 5., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## Pandas Dataframe (แยกออกไปเป็น Notebook เฉพาะ)

In [3]:
import numpy as np

In [4]:
arr2_23_15_5 = 5*np.ones((23,15))
arr2_23_15_5

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5.

In [35]:
HW = 5*np.ones((23,15))
HW

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5.

In [43]:
HW[1:4,7] = 1
HW[2:5,6] = 1
HW[2:5,8] = 1
HW[2:3,5] = 1
HW[2:3,9] = 1
HW[4:17,7] = 8
HW[5:17,6] = 8
HW[5:17,8] = 8
HW[6:17,5] = 8
HW[6:17,9] = 8
HW[7:8,4] = 8
HW[7:8,10] = 8
HW[9:17,4] = 8
HW[9:17,10] = 8
HW[10:11,3] = 8
HW[10:11,11] = 8
HW[12:17,3] = 8
HW[12:17,11] = 8
HW[13:14,2] = 8
HW[13:14,12] = 8
HW[15:17,2] = 8
HW[15:17,12] = 8
HW[16:17,1] = 8
HW[16:17,13] = 8
HW

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 1., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 1., 1., 1., 1., 1., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 1., 1., 1., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 1., 8., 1., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 8., 8., 8., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 8., 8., 8., 8., 8., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 8., 8., 8., 8., 8., 8., 8., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 8., 8., 8., 8., 8., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 8., 8., 8., 8., 8., 8., 8., 5., 5., 5., 5.],
       [5., 5., 5., 8., 8., 8., 8., 8., 8., 8., 8., 8., 5., 5., 5.],
       [5., 5., 5., 5., 8., 8., 8., 8., 8., 8., 8., 5., 5., 5., 5.],
       [5., 5., 5., 8., 8., 8., 8., 8., 8., 8., 8., 8., 5., 5., 5.],
       [5., 5., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 5., 5.],
       [5., 5., 5., 8., 8., 8., 8.

In [10]:
HWW = 5*np.ones((23,11))
HWW

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.

In [11]:
HWW[0:3,5] = 11
HWW[1:4,4] = 11
HWW[1:4,6] = 11
HWW[1:2,3] = 11
HWW[1:2,7] = 11
HWW[3:17,5] = 88
HWW[4:17,4] = 88
HWW[4:17,6] = 88
HWW[5:17,3] = 88
HWW[5:17,7] = 88
HWW[6:7,2] = 88
HWW[6:7,8] = 88
HWW[8:17,2] = 88
HWW[8:17,8] = 88
HWW

array([[ 5.,  5.,  5.,  5.,  5., 11.,  5.,  5.,  5.,  5.,  5.],
       [ 5.,  5.,  5., 11., 11., 11., 11., 11.,  5.,  5.,  5.],
       [ 5.,  5.,  5.,  5., 11., 11., 11.,  5.,  5.,  5.,  5.],
       [ 5.,  5.,  5.,  5., 11., 88., 11.,  5.,  5.,  5.,  5.],
       [ 5.,  5.,  5.,  5., 88., 88., 88.,  5.,  5.,  5.,  5.],
       [ 5.,  5.,  5., 88., 88., 88., 88., 88.,  5.,  5.,  5.],
       [ 5.,  5., 88., 88., 88., 88., 88., 88., 88.,  5.,  5.],
       [ 5.,  5.,  5., 88., 88., 88., 88., 88.,  5.,  5.,  5.],
       [ 5.,  5., 88., 88., 88., 88., 88., 88., 88.,  5.,  5.],
       [ 5.,  5., 88., 88., 88., 88., 88., 88., 88.,  5.,  5.],
       [ 5.,  5., 88., 88., 88., 88., 88., 88., 88.,  5.,  5.],
       [ 5.,  5., 88., 88., 88., 88., 88., 88., 88.,  5.,  5.],
       [ 5.,  5., 88., 88., 88., 88., 88., 88., 88.,  5.,  5.],
       [ 5.,  5., 88., 88., 88., 88., 88., 88., 88.,  5.,  5.],
       [ 5.,  5., 88., 88., 88., 88., 88., 88., 88.,  5.,  5.],
       [ 5.,  5., 88., 88., 88., 88., 88