<a href="https://colab.research.google.com/github/Narissarach/data_viz_2022/blob/main/Christmas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## HW 3 

1. สร้าง array ที่เป็นรูปต้น Christmas
2. slice เลข 1 ออกมาจาก array HW3

In [ ]:
HW3 = np.zeros((10,10))
HW3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
HW3[::4,2] = 6
HW3[::4,4] = 5
HW3[::4,6] = 1
HW3[::4,8] = 1
HW3

array([[0., 0., 6., 0., 5., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 6., 0., 5., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 6., 0., 5., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## Pandas Dataframe (แยกออกไปเป็น Notebook เฉพาะ)

In [ ]:
arr2_23_15_5 = 5*np.ones((23,15))
arr2_23_15_5

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5.

In [2]:
import numpy as np

In [3]:
HW = 5*np.ones((23,15))
HW

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5.

In [6]:
HW[1:4,7] = 1
HW[2:5,6] = 1
HW[2:5,8] = 1
HW[2:3,5] = 1
HW[2:3,9] = 1
HW[4:17,7] = 8
HW[5:17,6] = 8
HW[5:17,8] = 8
HW[6:17,5] = 8
HW[6:17,9] = 8
HW[7:8,4] = 8
HW[7:8,10] = 8
HW[9:17,4] = 8
HW[9:17,10] = 8
HW[10:11,3] = 8
HW[10:11,11] = 8
HW[12:17,3] = 8
HW[12:17,11] = 8
HW[13:14,2] = 8
HW[13:14,12] = 8
HW[15:17,2] = 8
HW[15:17,12] = 8
HW[16:17,1] = 8
HW[16:17,13] = 8
HW[17:21,7] = 9
HW[17:21,6] = 9
HW[17:21,8] = 9
HW

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 1., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 1., 1., 1., 1., 1., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 1., 1., 1., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 1., 8., 1., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 8., 8., 8., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 8., 8., 8., 8., 8., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 8., 8., 8., 8., 8., 8., 8., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 8., 8., 8., 8., 8., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 8., 8., 8., 8., 8., 8., 8., 5., 5., 5., 5.],
       [5., 5., 5., 8., 8., 8., 8., 8., 8., 8., 8., 8., 5., 5., 5.],
       [5., 5., 5., 5., 8., 8., 8., 8., 8., 8., 8., 5., 5., 5., 5.],
       [5., 5., 5., 8., 8., 8., 8., 8., 8., 8., 8., 8., 5., 5., 5.],
       [5., 5., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 5., 5.],
       [5., 5., 5., 8., 8., 8., 8.

In [56]:
HWW = np.ones((24,11))
HWW

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.

In [57]:
HWW[1:4,5] = 44
HWW[2:5,4] = 44
HWW[2:5,6] = 44
HWW[2:4,3] = 44
HWW[2:4,7] = 44
HWW[4:18,5] = 88
HWW[5:18,4] = 88
HWW[5:18,6] = 88
HWW[6:8,3] = 88
HWW[6:8,7] = 88
HWW[9:12,3] = 88
HWW[9:12,7] = 88
HWW[7:8,2] = 88
HWW[7:8,8] = 88
HWW[10:12,2] = 88
HWW[10:12,8] = 88
HWW[12:18,3] = 88
HWW[12:18,7] = 88
HWW[13:18,2] = 88
HWW[13:18,8] = 88
HWW[11:12,1] = 88
HWW[11:12,9] = 88
HWW[14:18,1] = 88
HWW[14:18,9] = 88
HWW[15:18,0] = 88
HWW[15:18,10] = 88
HWW[18:23,5] = 99
HWW[18:23,4] = 99
HWW[18:23,6] = 99
HWW

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1., 44.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1., 44., 44., 44., 44., 44.,  1.,  1.,  1.],
       [ 1.,  1.,  1., 44., 44., 44., 44., 44.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1., 44., 88., 44.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1., 88., 88., 88.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1., 88., 88., 88., 88., 88.,  1.,  1.,  1.],
       [ 1.,  1., 88., 88., 88., 88., 88., 88., 88.,  1.,  1.],
       [ 1.,  1.,  1.,  1., 88., 88., 88.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1., 88., 88., 88., 88., 88.,  1.,  1.,  1.],
       [ 1.,  1., 88., 88., 88., 88., 88., 88., 88.,  1.,  1.],
       [ 1., 88., 88., 88., 88., 88., 88., 88., 88., 88.,  1.],
       [ 1.,  1.,  1., 88., 88., 88., 88., 88.,  1.,  1.,  1.],
       [ 1.,  1., 88., 88., 88., 88., 88., 88., 88.,  1.,  1.],
       [ 1., 88., 88., 88., 88., 88., 88., 88., 88., 88.,  1.],
       [88., 88., 88., 88., 88., 88., 88